{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # name of the ingress resource. -ingress suffix as suggestion for clear naming convention
  name: {{ .Values.appName }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    # IMPORTANT: specifies the entrypoint (domain), myApp will be accessible from
    - host: {{ .Values.certificate.host }}
      http:
        paths:
          # specific path the app should be reachable on the host
          # complete URL for the app consists of host AND path
          - path: /
            pathType: Prefix
            backend:
              service:
                # Name of the service, the ingress controller should route the traffic to, if the host/path combination is called
                # Adjust that to your service name
                name: {{ include "vas.fullname" . }}-service
                port:
                  # Port number, the kubernetes service is listening on
                  # Adjust that to your services' port
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.certificate.host }}
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

{{- end }}
